name: Flutter Web
on:
  push:
    branches: 
      - main
    paths:
      - 'flutter/all_projects/**'
jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.TOKEN_GIT}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter config --enable-web
      - name: Download Dependencies
        run: |
          cd flutter/all_projects
          flutter pub get
      - name: Build
        run: |
          cd flutter/all_projects
          flutter build web --release
      - name: Update index.html
        run: |
          sed -i 's|<base href="/">|<base href=".">|g' flutter/all_projects/build/web/index.html
      - name: Deploy to Github Pages
        run: |
          cd flutter/all_projects/build/web
          git init
          git config --global init.defaultBranch main
          git config --global user.email iamcaominhtien@gmail.com
          git config --global user.name iamcaominhtien
          git status
          git remote add origin https://${{secrets.TOKEN_GIT}}@github.com/iamcaominhtien/phuong_excercise.git
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f
